---
name: ddu-souce-anyjump
description: anyjump source for ddu.vim
--

=pod

=head1 ddu-source-anyjump X<ddu-source-anyjump>

Source for non-LSP oriented definition|reference list.

Based on https://github.com/pechorin/any-jump.vim.

=head2 Contents X<ddu-source-anyjump-contents>

=over 0

=item * L<ddu-source-anyjump-installation|ddu-source-anyjump-installation>

=item * L<ddu-source-anyjump-dependencies|ddu-source-anyjump-dependencies>

=item * L<ddu-source-anyjump-examples|ddu-source-anyjump-examples>

=item * L<ddu-source-anyjump-params|ddu-source-anyjump-params>

=back

=head2 Installation X<ddu-source-anyjump-installation>

Use your favorite plugin manager or other.

=head2 Dependencies X<ddu-source-anyjump-dependencies>

ddu.vim and denops.vim are required.

=over 0

=item * https://github.com/Shougo/ddu.vim

=item * https://github.com/vim-denops/denops.vim

=item * https://github.com/BurntSushi/ripgrep

Need to set C<rg> in your PATH.

=back

=head2 Examples X<ddu-source-anyjump-examples>

Configuration:

=begin vim

call ddu#custom#patch_global(#{
    \   sourceParams: #{
    \     anyjump_definition: #{
    \       highlights: #{
    \         path: 'Normal',
    \         lineNr: 'Normal',
    \         word: 'Search',
    \       },
    \       removeCommentsFromResults: v:true,
    \     },
    \   },
    \   sourceParams: #{
    \     anyjump_definition: #{
    \       highlights: #{
    \         path: 'Normal',
    \         lineNr: 'Normal',
    \         word: 'Search',
    \       },
    \       removeCommentsFromResults: v:true,
    \       onlyCurrentFiletype: v:false,
    \     },
    \   },
    \ })

=end vim

How to use:

=begin vim

call ddu#start(#{
    \ ui: 'ff',
    \ sources: [#{
    \   name: 'anyjump_definition',
    \ }]
    \ })

call ddu#start(#{
    \ ui: 'ff',
    \ sources: [#{
    \   name: 'anyjump_reference',
    \ }]
    \ })

=end vim

=head2 Params X<ddu-source-anyjump-params>

=head3 C<anyjump_definition>

=over 0

=item * C<highlights> X<ddu-source-anyjump_definition-param-highlights>

Highlight groups for path, lineNr and search word.

Default: "Normal" for path and lineNr.
Default: "Search" for word.

=item * C<removeCommentsFromResults> X<ddu-source-anyjump_definition-param-removeCommentsFromResults>

Remove comments line from search results.

Default: C<true>

=back

=head3 C<anyjump_reference>

=over 0

=item * C<highlights> X<ddu-source-anyjump_reference-param-highlights>

see L<ddu-source-anyjump_definition-param-highlights>.

=item * C<removeCommentsFromResults> X<ddu-source-anyjump_reference-param-removeCommentsFromResults>

see L<ddu-source-anyjump_definition-param-removeCommentsFromResults>.

=item * C<onlyCurrentFiletype> X<ddu-source-anyjump_reference-param-onlyCurrentFiletype>

Search references only for current file type.

Default C<false>

=back

=cut
